#!/bin/bash
# VoiceMemoLiberator - Voice memo transcription and management tool
# Copyright (C) 2026 APPSTART LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Remove all build artifacts and generated files to produce a clean source tree.
# After running this, rebuild with:
#   npm install && scripts/build-nlm.sh && npm run tauri build

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "Cleaning build artifacts..."

# Rust compilation output (~7 GB)
rm -rf src-tauri/target

# Node.js dependencies
rm -rf node_modules

# Vite frontend build output
rm -rf dist

# Vite cache
rm -rf .vite

# Compiled sidecar binaries (rebuilt by scripts/build-nlm.sh)
rm -rf src-tauri/binaries/nlm-*

# Rust lockfile (regenerated by cargo on build)
rm -f src-tauri/Cargo.lock

# TypeScript build info
find . -name "*.tsbuildinfo" -delete

# Log files
find . -name "*.log" -not -path "./.git/*" -not -path "./.beads/*" -delete

# macOS metadata
find . -name ".DS_Store" -delete

echo "Clean complete."
